config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
 
  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end

  namespace :api do
    namespace :v1 do
       resources :users do
          resources :posts do
           resources :comments
           resources :likes
        end
  end
    end

  end

  root to: "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    can :read, Post
    return unless user.present?

    can :destroy, Post, author: user
    can :destroy, Comment, author: user
    can :create, Post, author: user
    can :create, Like
    can :create, Comment
    return unless user.admin?

    can :destroy, Post
    can :destroy, Comment
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: :User, foreign_key: :author_id
  belongs_to :post

  after_save :update_comment_counter
  after_destroy :update_comment_counter_after_destroy

  private

  def update_comment_counter
    post.increment!(:comment_counter)
  end

  def update_comment_counter_after_destroy
    post.decrement!(:comment_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: :User
  belongs_to :post

  after_save :update_like_counter

  private

  def update_like_counter
    post.increment!(:like_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: :User, foreign_key: :author_id
  has_many :comments
  has_many :likes
  validates :title, presence: true, length: { maximum: 250 }
  validates :comment_counter, :like_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def recent_five_comment
    comments.order(created_at: :desc).limit(5)
  end

  after_save :update_post_counter
  after_destroy :update_post_counter_destroy

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def update_post_counter_destroy
    author.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  # include Devise::JWT::RevocationStrategies::Denylist
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable,
         :jwt_authenticatable, jwt_revocation_strategy: self
  has_many :likes, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :posts, foreign_key: :author_id
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  enum status: { draft: 0, completed: 1, published: 2 }
  has_one_attached :photo

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    comment = Comment.all.where(author_id: params[:user_id], post_id: params[:post_id]).includes(:author)
    render json: comment
  end

  def create
    posts = Post.find(params[:post_id])
    current_user = User.find(params[:user_id])
    comment = Comment.new(comment_params)
    comment.author_id = current_user.id
    comment.post_id = posts.id

    if comment.save
      render json: comment, status: :created
    else
      render json: comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    post = user.posts
    render json: post
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery Prepend: true

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio photo])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    render :new, locals: { user: current_user }
  end

  def create
    post_id = params[:post_id].to_i
    post = Post.find(post_id)
    comment = Comment.new(text: params[:user][:text], author: current_user, post:)
    if comment.save
      flash[:success] = 'Comment created successfully!'
      redirect_to user_post_path(current_user, post)
    else
      flash.now[:error] = 'Something went wrong!'
      render :new, locals: { user: current_user }, status: 302
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.find_by(author: @user, post: @post, id: params[:id])

    if @comment.destroy
      flash[:success] = 'Post was successfully deleted'
    else
      flash[:error] = 'Comment not Deleted'
    end
    redirect_to user_posts_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post_id = params[:post_id].to_i
    post = Post.find(post_id)
    like = Like.new(author: current_user, post:)
    if like.save
      redirect_to user_post_path(current_user, post)
    else
      flash[:error] = 'Something went wrong!'
      render user_post_path(current_user, post)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.includes(:posts).find_by(id: params[:user_id])
  end

  # posts/new
  def show
    @post_id = params[:id]
    @post = Post.find_by(id: @post_id)
  end

  def new
    render :new, locals: { user: current_user }
  end

  def create
    check_param
    title = params[:user][:title]
    text = params[:user][:text]
    post = Post.new(title:, text:, comment_counter: 0, like_counter: 0, author: current_user)
    if post.save
      flash[:success] = 'Post created successfuly!'
      redirect_to user_posts_path
    else
      flash.now[:error] = 'Something went wrong!'
      render :new, locals: { user: current_user }
    end
  end

  def destroy
    user_id = params[:user_id].to_i
    @user = User.find(user_id)
    @post = Post.find_by(author: @user)
    if @post.destroy
      flash[:success] = 'Post Deleted!'
      redirect_to user_posts_path
    else
      flash.now[:error] = 'Something went wrong!'
      render :index, locals: { user: current_user }
    end
  end

  private

  def check_param
    params.require(:user).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @author = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
   <h4 style='color: red'><%=flash[:error]%></h4>

<%= form_with model: user, url: user_post_comments_path, method: :post, class: 'add-comment-form', scope: :user do |f| %>
<div>
<%= f.label :comment%> <br/>
<%= f.text_area :text, placeholder: 'Put your comment here!', size: '50x10'%>
</div>
<%= f.submit "Add Comment", class: 'btn-comment button'%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SiaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render '/header'%>
    <main>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= yield %>
    </main>
  <%= render '/footer'%>
  </body>
</html>

app/views/posts/_all_post.html.erb
<div class='post'>
    <%= link_to user_post_path(user, post), class:'user-link' do%>
    <h2>Title: <%= post.title%> </h2>
    <p><%= post.text%></p>
    <%end%>
    <p>Comments: <%= Comment.where(post: post).size%>, Likes: <%= Like.where(post: post).size%></p>
   <%if can? :destroy, post%>
    <%= button_to "Delete Post", "/users/#{user.id}/posts/#{post.id}", method: :delete, class: 'btn-comment button'%>
   <%end%>

</div>

app/views/posts/_comment.html.erb
<div class='comment'>
<h4>Users comment on this post</h4>
    <% post.recent_five_comment.each do |comment|%>
     <p><strong><%=comment.author.name%> </strong> : <span><%=comment.text%></span></p>
     <%if can? :destroy, Comment%>
       <%= button_to "Delete Comment", "/users/#{comment.author.id}/posts/#{comment.post.id}/comments/#{comment.id}", method: :delete, class: 'btn-comment button'%>

     <%end%>
      <%end%>
</div>

app/views/posts/index.html.erb
<div class='post-container'>
<h4 style='color:green'><%=  flash[:success] %> </h4>
<%if user_signed_in?%>
<%= button_to "Add post", new_user_post_path, method: 'get', form_class: 'comment-form', class: 'button'%>
<%end%>
<%= render '/users/user', user: @user %>

<div class='post-comment'>
<% Post.includes(:comments).where(author: @user).each do |post|%>
<%= render 'all_post', post: post, user: @user%>

<%= render 'comment', post: post%>
<%end%>
<%= link_to 'Pagination', users_path, class: 'btn-all-post button' %>
<div>

</div>

app/views/posts/new.html.erb
<h4 style='color:green'><%=  flash[:error] %> </h4>


<%= form_with model: user, url: user_posts_path, method: :post, scope: :user, class: 'add-comment-form' do |x|%>
<div>
<%= x.label :title%>
<%= x.text_field :title, required: true, placeholder: 'Your title...'%> 
<div>

<div>
<%= x.label :text, "Your Post"%>
<%= x.text_area :text, size: '50x10', required: true, placeholder: 'Your message...'%>
</div>
<%= x.submit "Add post", class: 'post-button button'%>

<%end%>

app/views/posts/show.html.erb
<div class='detail-post'>
   <h4 style='color: green'><%=flash[:success]%></h4>
    <div class='top-detail'>
     <strong>Posts # <%=@post.id%> by <%= @post.author.name%></strong>
     <strong>Comments: <%= @post.comment_counter || 0%>, Likes: <%= Like.where(post: @post).size%></strong>
    </div>
    <p class='desc'><%=@post.text%></p>
  <%if user_signed_in? %>
   <div class='comment-like-container'>
    <%= link_to "Add Comment", new_user_post_comment_path(@post.author, @post), class: 'btn-comment button'%>
    <%= button_to "Like",user_post_likes_path(@post.author, @post), form_class: 'like', class: 'btn-like button' %>
   </div>
   <%end%>

    <%= render 'comment', post: @post%>

</div>

app/views/users/_post.html.erb
<div class='post'>
<%= link_to user_post_path(user, post) , class:'user-link', id:'user-link' do%>
<h2>Post Title: <%= post.title%> </h2>
<p class='post-desc'><%= post.text%></p>
<%end%>
<p>Comments: <%= post.comment_counter || 0%>, Likes: <%= post.like_counter || 0%></p>
   <% if can? :destroy, post%>
    <%= button_to "Delete Post", "/users/#{user.id}/posts/#{post.id}", method: :delete, class: 'btn-comment button'%>
   <%end%>
</div>

app/views/users/_user.html.erb
<%= link_to user_path(user), class:'user-link' do %>
<div class='user-card'>
<%= image_tag (user.photo), class:'user-img'%>
<div class='card-body'>
    <h2 class='user-name'><%= user.name%></h2>
    <p class ='number-of-post'>Number of posts: <%= user.posts_counter || 0 %></p>
</div>
</div>
<%end%>

app/views/users/index.html.erb
<div class='user-container'>
<h1>Welcome to siy blog</h1>
    <% @author.each do |user|%>
    <%= render 'user', user: user %>
    <%end%>
</div>

app/views/users/show.html.erb
<div class='user-posts'>
<%= render 'user', user: @user %>

    <div class='bio-container'>
    <h2>Bio </h2>
    <p class='bio'><%= @user.bio%> </p>
    </div>

 <%@user.recent_post.each do |post|%>
    <%= render 'post', post: post, user:post.author %>
 <%end%>

<%= link_to 'See all post', user_posts_path(@user), class: 'btn-all-post button'%>

</div>